Remove Gibson and Visual Servo.
PickNikRobotics/moveit_studio_ws pull request #171
Opened 2024-01-09 21:51 UTC by chancecardona

This is part of https://github.com/PickNikRobotics/moveit_studio/pull/5843 and removes these two no longer used dependencies. I'm not sure if this is correctly how you define an empty plugin list in yaml though so worth double checking.

2024-01-09 21:55 UTC, eholum approved these changes

2024-01-09 22:03 UTC, eholum requested changes
Actually can we delete the servoing objective?

2024-01-09 22:15 UTC, EzraBrooks commented on src/picknik_ur_site_config/config/config.yaml
> +  behavior_loader_plugins: []
I think this is of type dictionary, not array.

```suggestion
  behavior_loader_plugins: {}
```

2024-01-10 03:29 UTC, sea-bass requested changes
The integration test fixes are in https://github.com/PickNikRobotics/moveit_studio_ws/pull/166, so no need to do anything here -- instead we need to merge down `v3.0` into `main`. So revert those changes here and we can merge this in.

2024-01-11 04:55 UTC, sea-bass commented on src/picknik_ur_studio_integration_testing/picknik_ur_studio_integration_testing/generate_agent_plus_drivers_launch_description.py
> +        get_package_share_directory("picknik_ur_studio_integration_testing"),
revert this change as it's incoming in other PRs

2024-01-11 04:55 UTC, sea-bass commented on src/picknik_ur_studio_integration_testing/picknik_ur_studio_integration_testing/generate_agent_plus_drivers_launch_description.py
> +        get_package_share_directory("picknik_ur_studio_integration_testing"),
same here, revert this change as it's incoming in other PRs

2024-01-11 16:18 UTC, sea-bass approved these changes

2024-01-11 16:25 UTC, merged